J.D. :- https://www.metacareers.com/jobs/624841835890795/

In [1]:
! pip install docx2txt

Requirement already satisfied: docx2txt in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (0.8)

In [2]:
! pip install pdfplumber

Requirement already satisfied: pdfplumber in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (0.11.4)
Requirement already satisfied: pdfminer.six==20231228 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from pdfplumber) (20231228)
Requirement already satisfied: Pillow>=9.1 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from pdfplumber) (10.4.0)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from pdfplumber) (4.30.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from pdfminer.six==20231228->pdfplumber) (2.1.1)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from pdfminer.six==20231228->pdfplumber) (43.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in c:\users\chirag verma\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (2.22)

In [3]:
import os

import docx2txt
import pdfplumber

import numpy as np
import pandas as pd

import re

In [4]:
# https://www.kaggle.com/datasets/snehaanbhawal/resume-dataset?resource=download-directory&select=data

# dataset source 

path = 'ENGINEERING/'

file_names = os.listdir(path)

print("Number of Resumes:", len(file_names))

print("File Names (First 5 resumes):")
print(file_names[:5])

Number of Resumes: 432
File Names (First 5 resumes):
['10182582.pdf', '10186968.pdf', '10344379.pdf', '10554236.pdf', '10562768.pdf']

In [5]:
file_extensions = []
for file_name in os.listdir(path):
    file_extensions.append(os.path.splitext(file_name)[-1])
    
print(set(file_extensions))

{'.pdf'}

In [6]:
def extract_text_from_pdf(file_path):
    file_path = path+file_name
    text = ''
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            text += page.extract_text()
    return text

In [7]:
# removed 1000+ datasets cause extracting text was difficult for my slow computer

df = pd.DataFrame(columns = ['file_name', 'text'])

for file_name in os.listdir(path):
    file_path = path+file_name
    text = ''
    if file_name.endswith(".pdf"):
        try:
            text = extract_text_from_pdf(file_path)
        except:
            print("PDF Error for:", file_path)
    
    if text:
        df.loc[len(df)] = [file_name, text]
        
df.head()

PDF Error for: ENGINEERING/24416961.pdf
PDF Error for: ENGINEERING/24516163.pdf
PDF Error for: ENGINEERING/24533931.pdf
PDF Error for: ENGINEERING/24588864.pdf
PDF Error for: ENGINEERING/24695561.pdf
PDF Error for: ENGINEERING/24754689.pdf
PDF Error for: ENGINEERING/24763208.pdf
PDF Error for: ENGINEERING/24946537.pdf
PDF Error for: ENGINEERING/24989856.pdf
PDF Error for: ENGINEERING/25142074.pdf
PDF Error for: ENGINEERING/25543217.pdf
PDF Error for: ENGINEERING/25873425.pdf
PDF Error for: ENGINEERING/26046878.pdf
PDF Error for: ENGINEERING/26070334.pdf
PDF Error for: ENGINEERING/26071861.pdf
PDF Error for: ENGINEERING/26098594.pdf
PDF Error for: ENGINEERING/26456474.pdf
PDF Error for: ENGINEERING/26586477.pdf
PDF Error for: ENGINEERING/26691587.pdf
PDF Error for: ENGINEERING/26829561.pdf
PDF Error for: ENGINEERING/26835781.pdf
PDF Error for: ENGINEERING/26921245.pdf
PDF Error for: ENGINEERING/27091280.pdf
PDF Error for: ENGINEERING/27099856.pdf
PDF Error for: ENGINEERING/27176039.pdf
PDF Error for: ENGINEERING/27182111.pdf
PDF Error for: ENGINEERING/27549075.pdf
PDF Error for: ENGINEERING/27689009.pdf
PDF Error for: ENGINEERING/27694040.pdf
PDF Error for: ENGINEERING/27888251.pdf
PDF Error for: ENGINEERING/28111403.pdf
PDF Error for: ENGINEERING/28165687.pdf
PDF Error for: ENGINEERING/28206098.pdf
PDF Error for: ENGINEERING/28247753.pdf
PDF Error for: ENGINEERING/28635795.pdf
PDF Error for: ENGINEERING/28733974.pdf
PDF Error for: ENGINEERING/28871170.pdf
PDF Error for: ENGINEERING/28974459.pdf
PDF Error for: ENGINEERING/28998957.pdf
PDF Error for: ENGINEERING/29028935.pdf
PDF Error for: ENGINEERING/29142288.pdf
PDF Error for: ENGINEERING/29173771.pdf
PDF Error for: ENGINEERING/29177904.pdf
PDF Error for: ENGINEERING/29415426.pdf
PDF Error for: ENGINEERING/29510501.pdf
PDF Error for: ENGINEERING/29521434.pdf
PDF Error for: ENGINEERING/29640922.pdf
PDF Error for: ENGINEERING/29746235.pdf
PDF Error for: ENGINEERING/29764492.pdf
PDF Error for: ENGINEERING/29897742.pdf
PDF Error for: ENGINEERING/29926588.pdf
PDF Error for: ENGINEERING/29968330.pdf
PDF Error for: ENGINEERING/30344127.pdf
PDF Error for: ENGINEERING/30430249.pdf
PDF Error for: ENGINEERING/30437583.pdf
PDF Error for: ENGINEERING/30741799.pdf
PDF Error for: ENGINEERING/31040875.pdf
PDF Error for: ENGINEERING/31225895.pdf
PDF Error for: ENGINEERING/31242382.pdf
PDF Error for: ENGINEERING/31362807.pdf
PDF Error for: ENGINEERING/31761591.pdf
PDF Error for: ENGINEERING/32965335.pdf
PDF Error for: ENGINEERING/33665485.pdf
PDF Error for: ENGINEERING/34141299.pdf
PDF Error for: ENGINEERING/34327438.pdf
PDF Error for: ENGINEERING/34970271.pdf
PDF Error for: ENGINEERING/35121930.pdf
PDF Error for: ENGINEERING/35344611.pdf
PDF Error for: ENGINEERING/35474904.pdf
PDF Error for: ENGINEERING/35571205.pdf
PDF Error for: ENGINEERING/35603950.pdf
PDF Error for: ENGINEERING/35985133.pdf
PDF Error for: ENGINEERING/36094883.pdf
PDF Error for: ENGINEERING/36102323.pdf
PDF Error for: ENGINEERING/36136569.pdf
PDF Error for: ENGINEERING/36392131.pdf
PDF Error for: ENGINEERING/36694627.pdf
PDF Error for: ENGINEERING/37201447.pdf
PDF Error for: ENGINEERING/37292350.pdf
PDF Error for: ENGINEERING/37333719.pdf
PDF Error for: ENGINEERING/37348041.pdf
PDF Error for: ENGINEERING/37560528.pdf
PDF Error for: ENGINEERING/37640804.pdf
PDF Error for: ENGINEERING/37750854.pdf
PDF Error for: ENGINEERING/38059130.pdf
PDF Error for: ENGINEERING/38216888.pdf
PDF Error for: ENGINEERING/38291889.pdf
PDF Error for: ENGINEERING/38698573.pdf
PDF Error for: ENGINEERING/38860712.pdf
PDF Error for: ENGINEERING/40088790.pdf
PDF Error for: ENGINEERING/40882926.pdf
PDF Error for: ENGINEERING/41586420.pdf
PDF Error for: ENGINEERING/42164460.pdf
PDF Error for: ENGINEERING/43852883.pdf
PDF Error for: ENGINEERING/44115326.pdf
PDF Error for: ENGINEERING/46514339.pdf
PDF Error for: ENGINEERING/46772262.pdf
PDF Error for: ENGINEERING/47133747.pdf
PDF Error for: ENGINEERING/49475708.pdf
PDF Error for: ENGINEERING/49486820.pdf
PDF Error for: ENGINEERING/50324968.pdf
PDF Error for: ENGINEERING/52252936.pdf
PDF Error for: ENGINEERING/53169257.pdf
PDF Error for: ENGINEERING/54067174.pdf
PDF Error for: ENGINEERING/54246169.pdf
PDF Error for: ENGINEERING/54308684.pdf
PDF Error for: ENGINEERING/55500538.pdf
PDF Error for: ENGINEERING/55712978.pdf
PDF Error for: ENGINEERING/56025640.pdf
PDF Error for: ENGINEERING/56068028.pdf
PDF Error for: ENGINEERING/56151548.pdf
PDF Error for: ENGINEERING/58208591.pdf
PDF Error for: ENGINEERING/62994611.pdf
PDF Error for: ENGINEERING/69336473.pdf
PDF Error for: ENGINEERING/69360287.pdf
PDF Error for: ENGINEERING/69859102.pdf
PDF Error for: ENGINEERING/70750649.pdf
PDF Error for: ENGINEERING/71499299.pdf
PDF Error for: ENGINEERING/71767359.pdf
PDF Error for: ENGINEERING/72652441.pdf
PDF Error for: ENGINEERING/72807293.pdf
PDF Error for: ENGINEERING/73448369.pdf
PDF Error for: ENGINEERING/74126637.pdf
PDF Error for: ENGINEERING/74191424.pdf
PDF Error for: ENGINEERING/75057933.pdf
PDF Error for: ENGINEERING/75435017.pdf
PDF Error for: ENGINEERING/75950464.pdf
PDF Error for: ENGINEERING/77439230.pdf
PDF Error for: ENGINEERING/78273826.pdf
PDF Error for: ENGINEERING/78538268.pdf
PDF Error for: ENGINEERING/79536879.pdf
PDF Error for: ENGINEERING/80503242.pdf
PDF Error for: ENGINEERING/81042872.pdf
PDF Error for: ENGINEERING/83566455.pdf
PDF Error for: ENGINEERING/84512719.pdf
PDF Error for: ENGINEERING/89508407.pdf
PDF Error for: ENGINEERING/89740812.pdf
PDF Error for: ENGINEERING/90468982.pdf
PDF Error for: ENGINEERING/91026230.pdf
PDF Error for: ENGINEERING/91051945.pdf
PDF Error for: ENGINEERING/91533580.pdf
PDF Error for: ENGINEERING/93512385.pdf
PDF Error for: ENGINEERING/95714702.pdf
PDF Error for: ENGINEERING/95970987.pdf
PDF Error for: ENGINEERING/97405769.pdf
PDF Error for: ENGINEERING/99806115.pdf

      file_name                                               text
0  10182582.pdf  KEY HOLDER\nSummary\nHighly organized efficien...
1  10186968.pdf  CHILD FAMILY ADVOCATE\nProfessional Profile\nT...
2  10344379.pdf  Summary\nAdministrative support professional w...
3  10554236.pdf  ACCOUNTANT\nSummary\nFinancial Accountant spec...
4  10562768.pdf  ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...

In [8]:
%%time

email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(?!\.)'
phone_pattern = r'\+?\d{1,4}[\d -]{8,12}\d'

def extract_email(content):
    email = re.findall(email_pattern, content)
    return email

def extract_phone(content):
    phone = re.findall(phone_pattern, content)
    return phone

df['emails'] = df['text'].apply(lambda x: extract_email(x))
df['phone_numbers'] = df['text'].apply(lambda x : extract_phone(x))

df.head()

CPU times: total: 109 ms
Wall time: 250 ms

,file_name,text,emails,phone_numbers
0,10182582.pdf,KEY HOLDER\nSummary\nHighly organized efficien...,[],[]
1,10186968.pdf,CHILD FAMILY ADVOCATE\nProfessional Profile\nT...,[],[]
2,10344379.pdf,Summary\nAdministrative support professional w...,[],[]
3,10554236.pdf,ACCOUNTANT\nSummary\nFinancial Accountant spec...,[],[]
4,10562768.pdf,ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...,[],[]

In [9]:
# based on J.D. , manually update the skillset_score

skillset_score = {
    "Python": 2,
    "regression": 2,
    "machine learning": 2,
    "recommendation system": 2,
    "pytorch" : 2 
}

skillset_score.keys()

dict_keys(['Python', 'regression', 'machine learning', 'recommendation system', 'pytorch'])

In [10]:
regex = '(' + '|'.join(skillset_score.keys()) + ')'

regex

'(Python|regression|machine learning|recommendation system|pytorch)'

In [11]:
%%time

df['skillset'] = df['text'].apply(lambda x : re.findall(regex, x.lower()))

df.head()

CPU times: total: 46.9 ms
Wall time: 71 ms

,file_name,text,emails,phone_numbers,skillset
0,10182582.pdf,KEY HOLDER\nSummary\nHighly organized efficien...,[],[],[]
1,10186968.pdf,CHILD FAMILY ADVOCATE\nProfessional Profile\nT...,[],[],[]
2,10344379.pdf,Summary\nAdministrative support professional w...,[],[],[]
3,10554236.pdf,ACCOUNTANT\nSummary\nFinancial Accountant spec...,[],[],[]
4,10562768.pdf,ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...,[],[],[]

In [12]:
df['skillset'] = df['skillset'].apply(lambda x : list(set(x)))

df.head()

,file_name,text,emails,phone_numbers,skillset
0,10182582.pdf,KEY HOLDER\nSummary\nHighly organized efficien...,[],[],[]
1,10186968.pdf,CHILD FAMILY ADVOCATE\nProfessional Profile\nT...,[],[],[]
2,10344379.pdf,Summary\nAdministrative support professional w...,[],[],[]
3,10554236.pdf,ACCOUNTANT\nSummary\nFinancial Accountant spec...,[],[],[]
4,10562768.pdf,ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...,[],[],[]

In [13]:
df_skills = df.explode('skillset')

df_skills.head()

,file_name,text,emails,phone_numbers,skillset
0,10182582.pdf,KEY HOLDER\nSummary\nHighly organized efficien...,[],[],NaN
1,10186968.pdf,CHILD FAMILY ADVOCATE\nProfessional Profile\nT...,[],[],NaN
2,10344379.pdf,Summary\nAdministrative support professional w...,[],[],NaN
3,10554236.pdf,ACCOUNTANT\nSummary\nFinancial Accountant spec...,[],[],NaN
4,10562768.pdf,ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...,[],[],NaN

In [14]:
df_skills.shape

(287, 5)

In [15]:
df_skills['skillset_score'] = df_skills['skillset'].apply(lambda x : skillset_score.get(x))

df_skills.head(20)

,file_name,text,emails,phone_numbers,skillset,skillset_score
0,10182582.pdf,KEY HOLDER\nSummary\nHighly organized efficien...,[],[],NaN,NaN
1,10186968.pdf,CHILD FAMILY ADVOCATE\nProfessional Profile\nT...,[],[],NaN,NaN
2,10344379.pdf,Summary\nAdministrative support professional w...,[],[],NaN,NaN
3,10554236.pdf,ACCOUNTANT\nSummary\nFinancial Accountant spec...,[],[],NaN,NaN
4,10562768.pdf,ASSISTANT BANKING CENTER MANAGER I\nSummary\nE...,[],[],NaN,NaN
5,10659182.pdf,SUBSTITUTE TEACHER\nProfessional Summary\nA se...,[],[],NaN,NaN
6,10674770.pdf,STAFF ACCOUNTANT\nSummary\nHighly analytical a...,[],[],NaN,NaN
7,10738095.pdf,INDEPENDENT BEAUTY ADVISOR\nCareer Overview\nT...,[],[],NaN,NaN
8,10818478.pdf,EXPRESS SCRIPTS\nSummary\nResponsible and matu...,[],[],NaN,NaN
9,10830646.pdf,TUTORING CONSULTANT\nExecutive Profile\nMotiva...,[],[],NaN,NaN
10,10876132.pdf,SPECIAL INVESTIGATIVE UNIT I\nSummary\nEnerget...,[],[],NaN,NaN
11,10953078.pdf,RN STAFF NURSE\nProfessional Experience\nRN St...,[],[],NaN,NaN
12,11163645.pdf,ACCOUNTANT\nProfessional Summary\nTo obtain a ...,[],[2 864-472-7092],NaN,NaN
13,11174187.pdf,RN / ASST. HEAD NURSE PRACTICE LEADER\nSkills\...,[],[],NaN,NaN
14,11187796.pdf,MICHAEL'S ARTS AND CRAFTS STORE\nSummary\nI am...,[],[],NaN,NaN
15,11188218.pdf,CUSTOMER ADVOCATE\nCareer Overview\nObjective ...,[],[],NaN,NaN
16,11197262.pdf,PLANT PROTECTION AND QUARANTINE TECHNICIAN\nSu...,[],[],NaN,NaN
17,11232471.pdf,SOFTLINES MANAGER\nSummary\nExperienced Retail...,[],[],NaN,NaN
18,11360471.pdf,MATERIAL AND TOOLING CONTROL LEAD\nSummary\nQu...,[],[],NaN,NaN
19,11409460.pdf,"BUYER/PLANNER\nSummary\nDetail-oriented, analy...",[],[],NaN,NaN

In [16]:
grouped_df = df_skills.groupby('file_name')

grouped_df['skillset_score'].sum()

file_name
10182582.pdf         0.0
10186968.pdf         0.0
10344379.pdf         0.0
10554236.pdf         0.0
10562768.pdf         0.0
                    ...
80053367.pdf         0.0
82649935.pdf         0.0
87635012.pdf         0.0
98559931.pdf         0.0
Resume Chirag.pdf    4.0
Name: skillset_score, Length: 286, dtype: float64

In [17]:
profile_scores = grouped_df['skillset_score'].sum()

profile_scores.head()

file_name
10182582.pdf    0.0
10186968.pdf    0.0
10344379.pdf    0.0
10554236.pdf    0.0
10562768.pdf    0.0
Name: skillset_score, dtype: float64

In [18]:
sorted_profile_scores = profile_scores.sort_values(ascending = False)

sorted_profile_scores

file_name
Resume Chirag.pdf    4.0
39115899.pdf         2.0
12202337.pdf         2.0
10562768.pdf         0.0
10659182.pdf         0.0
                    ...
11813872.pdf         0.0
11963737.pdf         0.0
11995013.pdf         0.0
12059610.pdf         0.0
10554236.pdf         0.0
Name: skillset_score, Length: 286, dtype: float64

In [21]:
sorted_profile_scores[sorted_profile_scores >= 2.0]

file_name
Resume Chirag.pdf    4.0
39115899.pdf         2.0
12202337.pdf         2.0
Name: skillset_score, dtype: float64